
---
#fisrt we will install the repo for docker_ce
# 2) will install docker
#installing Docker, changee Hosts ip or group to your needs
- hosts: k8_cluster
  tasks:
    - name: installing docker repo
      yum_repository:
        name: docker_ce-repo
        description: repo Docker-ce
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        enabled: yes
        gpgcheck: no

#installing docker latest
    - name: docker newest installation
      yum:
        name: docker
        state: latest
